version: "3.8"

services:
  api_gateway:
    build:
      context: ./API_gateway/
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
  
  file_upload_worker:
    build:
      context: ./services/file_upload
    container_name: file_upload
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"